workflows:
  ios-native-workflow:
    name: iOS Native
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Easter-parsons
    environment: 
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.remote.test.app
      vars:
        BUNDLE_ID: "com.remote.test.app"
        XCODE_WORKSPACE: "New Smart.xcworkspace"
        XCODE_SCHEME: "New Smart"
        APP_STORE_APPLE_ID: 6754910105
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          pod install
      - name: Resolve Swift Package Dependencies
        script: |
          cd $CM_BUILD_DIR
          xcodebuild -resolvePackageDependencies -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -derivedDataPath DerivedData
      - name: Install Codemagic CLI tools
        script: |
          pip3 install codemagic-cli-tools
      - name: Fetch code signing
        script: |
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles
      - name: Set up provisioning profiles settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Strip simulator architectures from SmartView framework
        script: |
          echo "Stripping simulator architectures from SmartView framework..."
          FRAMEWORK_PATH="./Frameworks/SmartView.framework/SmartView"
          if [ -f "$FRAMEWORK_PATH" ]; then
            echo "Original framework info:"
            lipo -info "$FRAMEWORK_PATH"

            # Check if x86_64 exists and remove it
            if lipo -info "$FRAMEWORK_PATH" | grep -q "x86_64"; then
              echo "Removing x86_64 architecture..."
              lipo -remove x86_64 -output "${FRAMEWORK_PATH}_temp" "$FRAMEWORK_PATH"
              mv "${FRAMEWORK_PATH}_temp" "$FRAMEWORK_PATH"
            fi

            # Check if i386 exists and remove it
            if lipo -info "$FRAMEWORK_PATH" | grep -q "i386"; then
              echo "Removing i386 architecture..."
              lipo -remove i386 -output "${FRAMEWORK_PATH}_temp" "$FRAMEWORK_PATH"
              mv "${FRAMEWORK_PATH}_temp" "$FRAMEWORK_PATH"
            fi

            # Remove simulator Swift modules
            echo "Removing simulator Swift modules..."
            find "./Frameworks/SmartView.framework/Modules/SmartView.swiftmodule" -name "*simulator*" -delete 2>/dev/null || true

            echo "Framework stripping completed. Final framework info:"
            lipo -info "$FRAMEWORK_PATH"
          else
            echo "SmartView framework not found at expected path"
          fi
      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Debug Xcode build and archive
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration
        submit_to_app_store: true